using DevExpress.XtraPrinting;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DevExpressPivot
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            userTableAdapter2.Fill(yongheonDBDataSet2.User);
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        /// <summary>
        /// Pivot을 Excel 로 Export
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void btnExport_Click(object sender, EventArgs e)
        {
            const string path = @"D:\PivotGrid.xlsx";

            pivotGridControl1.ExportToXlsx(path, new XlsxExportOptionsEx
            {
                AllowGrouping = DevExpress.Utils.DefaultBoolean.False,
                AllowFixedColumnHeaderPanel = DevExpress.Utils.DefaultBoolean.False
            });

            System.Diagnostics.Process.Start(path);
        }
    }
}
